name:                haskell-santa-problem
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- nonempty-containers
- async
- stm
- concurrency
- mtl
- optparse-applicative
- aeson
- neat-interpolation
- ansi-terminal

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages

library:
  source-dirs: src

executables:
  haskell-santa-problem:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-santa-problem

tests:
  haskell-santa-problem-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-santa-problem
    - hspec
    - hspec-discover
    - QuickCheck
    - dejafu
    - hunit-dejafu

verbatim:
  cabal-version: 3.0
